### PR TITLE
Removed decoding from Body Template Expansion

### LINKED ISSUE #916: Body contains % ,  as JSON, UriUtils.decode error
Request Body
`{
      "percent" : "100%",
      "name" : "lee"
}`

Feign client  declarative invocation will decode throw exception
 URLDecoder.decode() code `throw new IllegalArgumentException(
                                   "URLDecoder: Illegal hex characters in escape "
                                            + "(%) pattern - negative value");`

UriUtils.decode()  should be contain IllegalArgumentException,  return the original value .

### PR DESCRIPTION
**Pull request by kdavisk6**
Fixes #916

In certain cases, a Body Template will contain a JSON payload.  To
support this we are asking users to pct-encode the beginning and the
end of the JSON object when providing it to the RequestLine so we don't
reject it as an expression.  Doing this requires that the we decode those
markers before submitting the request.

This change updates that logic to only decode the first and last characters
only and not decode the entire payload, since Body values don't require
any type of encoding.

### CODE REVIEW

File: core/src/main/java/feign/template/BodyTemplate.java [hunk 1]
```diff
@@ -35,10 +41,24 @@ public static BodyTemplate create(String template) {
...
   public String expand(Map<String, ?> variables) {
-    return UriUtils.decode(super.expand(variables), Util.UTF_8);
+    String expanded = super.expand(variables);
+    if (this.json) {
+      /* decode only the first and last character */
+      expanded = expanded.substring(
+          expanded.indexOf(JSON_TOKEN_START_ENCODED) + JSON_TOKEN_START_ENCODED.length());
+      expanded = JSON_TOKEN_START + expanded;
+      expanded = expanded.substring(0, expanded.lastIndexOf(JSON_TOKEN_END_ENCODED));
+      expanded += JSON_TOKEN_END;
```
Comment (velo) [inline core/src/main/java/feign/template/BodyTemplate.java]: Shouldn't we be using a `StringBuilder` ?

Comment (kdavisk6) [reply core/src/main/java/feign/template/BodyTemplate.java]: Yes, that would be better.  I'll make the changes.
