### PR TITLE
Aggregate Micrometer "uri" label values under uri template

### LINKED ISSUE #1481: Feign Micrometer processes slugs in URIs
When I'm looking at requests sent to prometheus, this is what I expect to see:
`http_server_requests_seconds_count{exception="ExternalException",method="GET",outcome="SERVER_ERROR",status="500",uri="/api/v1/userdetails/{userId}",} 2.0`
Notice the unexpended slug.

However, with feign client, this is what I receive:
`feign_Client_seconds_count{client="net.corp.integration.MyClient",host="anotherServer.net",method="findCustomerById",uri="https://anotherServer.net/api/v2/customers/12347",} 4.0`

Notice the expanded slug. With every different customerId I'll get a different log entry rather than a grouping.

I've done some digging and it seems that the MeteredClient works with an expanded requestTemplate rather than the original. I've also noticed that at some point in the execution the original requet template is replaced by the resolved template. I'm not sure where that's happpening and I'd gladly submit a MR if somebody would present a solution to this.

Feign micrometer version: 11.5

### PR DESCRIPTION
**Pull request by martinacat**
# Overview
Use path expression rather than explicit value for Micrometer `uri` labels

This new default means that the value of the `uri` metric label becomes `/get/{id}` rather than `/get/123`

* Changes the default value of the `uri` label
* Adds a bunch of new unit tests around that feature

# Motivation
This change provides better aggregation, protecting time series databases such as Prometheus from a large influx of time series (high-cardinality metrics).

Currently - as noted in #1481 - enabling feign client metrics from config on clients with a parametrized urls creates a scenario where a new time series is produced for each value of the provided parameter. This provides extremely high-cardinality metrics at a fast rate endangering the underlying time series database. (Resolves #1481, related to #873)

When traffic is significant, collecting client metrics with an uri expression such as `reservation/{reservationId}` can generate tens of thousands of time series (one for each value of the label, a potentially infinite set), putting Prometheus at risk. Enabling OOTB metrics without being aware of the high cardinality of some metrics is quite easy to do, so we thought we could protect some users by changing the default behavior 

# Testing
* Unit tests written
* Approach was also tested on one of my existing applications as described in this [comment](https://github.com/OpenFeign/feign/issues/1481#issuecomment-906349520)

Screen Shot 2021-08-26 at 12 38 08 PM

# Questions
* Is there any integration or regression tests that are worth expanding to cover this feature?
* Which CHANGELOG can I add this feature to? 

Thank you for your time! 😊

### CODE REVIEW

File: micrometer/src/main/java/feign/micrometer/MeteredClient.java [hunk 1]
```diff
@@ -83,9 +83,9 @@ protected void countResponseCode(Request request,
     final RequestTemplate template = request.requestTemplate();
     final Tags allTags = metricTagResolver
         .tag(template.methodMetadata(), template.feignTarget(), e,
-            new Tag[] {Tag.of("http_status", String.valueOf(responseStatus)),
-                Tag.of("status_group", responseStatus / 100 + "xx"),
-                Tag.of("uri", template.path())})
+            Tag.of("http_status", String.valueOf(responseStatus)),
+            Tag.of("status_group", responseStatus / 100 + "xx"),
+            Tag.of("uri", template.methodMetadata().template().path()))
```
[the remark this answers is not in the document]
Comment (velo) [reply micrometer/src/main/java/feign/micrometer/MeteredClient.java:88]: I think NPE is only likely for a manually created RequestTemplate.

**Review by velo — APPROVED** [review]

File: micrometer/src/test/java/feign/micrometer/MicrometerCapabilityTest.java [hunk 2]
```diff
@@ -18,19 +18,96 @@
...
+
+  public interface SourceWithPathExpressions {
+
+    @RequestLine("GET /get/{id}")
+    String get(@Param("id") String id, String body);
+
+  }
+
+  @Test
+  public void clientMetricsHaveUriLabel() {
```
Comment (velo) [inline micrometer/src/test/java/feign/micrometer/MicrometerCapabilityTest.java:51]: Can we move this tests to the `AbstractMetricsTestBase`, likely this will fail for `dropwizard-metrics` which would need to be made consistent.

File: micrometer/src/main/java/feign/micrometer/MeteredClient.java (hunk 1 above)
[the remark this answers is not in the document]
Comment (martinacat) [reply micrometer/src/main/java/feign/micrometer/MeteredClient.java:88]: Thank you!

File: micrometer/src/test/java/feign/micrometer/MicrometerCapabilityTest.java (hunk 2 above)
Comment (martinacat) [reply micrometer/src/test/java/feign/micrometer/MicrometerCapabilityTest.java:51]: I see - I originally placed it in `AbstractMetricsTestBase`, however I realised that `dropwizard-metrics` don't attach `uri` and thought that was a design decision. If necessary I can add `uri` on dropwizard 4 and 5 - is that what we would like? Thanks!

Comment (martinacat) [reply micrometer/src/test/java/feign/micrometer/MicrometerCapabilityTest.java]: I have moved the tests in `AbstractMetricsTestBase` and made `dropwizard-metrics` 4 & 5 consistent :)

**Review by velo — APPROVED** [review]
