### PR TITLE
Fix exception thrown when using a custom error decoder with metrics

### LINKED ISSUE #1466: Exception Metrics cause IllegalArgumentException when using custom ErrorDecoders
Seems like the `MeteredInvocationHandleFactory` in `feign-micrometer` 11.5 tries to create both a timer and counter with the same name when using a custom error decoder that does not return a subclass of `FeignException`. This results in the following exception:

```
Caused by: java.lang.IllegalArgumentException: There is already a registered meter of a different type with the same name
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:571)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:561)
	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:284)
	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:128)
	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:391)
	at feign.micrometer.MeteredInvocationHandleFactory.createExceptionCounter(MeteredInvocationHandleFactory.java:108)
	at feign.micrometer.MeteredInvocationHandleFactory.lambda$create$0(MeteredInvocationHandleFactory.java:85)
	at com.sun.proxy.$Proxy128.getById(Unknown Source)
```

I have created [this repo](https://github.com/DarkAtra/openfeign-metrics-issue) to demonstrate the issue (refer to the tests).

### PR DESCRIPTION
**Pull request by DarkAtra**
Fixes #1466

### CODE REVIEW

File: micrometer/src/main/java/feign/micrometer/MeteredInvocationHandleFactory.java [hunk 1]
```diff
@@ -67,22 +67,15 @@ public InvocationHandler create(Target target, Map<Method, MethodHandler> dispat
...
       Timer timer = null;
       try {
-        try {
-          final Object invoke = invocationHandle.invoke(proxy, method, args);
-          timer = createTimer(target, method, args, null);
-          return invoke;
-        } catch (Exception e) {
-          throw e;
-        } catch (Throwable e) {
-          throw new Exception(e);
```
Comment (velo) [inline micrometer/src/main/java/feign/micrometer/MeteredInvocationHandleFactory.java:77]: I saw no reason to have this layer of try catches... removed

**Review by velo — APPROVED** [review]
